#!/bin/bash
# =============================================================================
# KDD - Database Discovery and Configuration Generator
# =============================================================================
# Scans running Docker containers and generates config.yaml for backups
# Supports: MySQL/MariaDB, PostgreSQL, MongoDB
#
# Usage:
#   # Automatic mode (add all databases found)
#   docker run --rm -v ... kdd:latest /app/setup.sh
#
#   # Interactive mode (ask for each database)
#   docker run --rm -it -v ... kdd:latest /app/setup.sh --interactive
# =============================================================================

set -e

CONFIG="/config/config.yaml"
DOCKER_ROOT="${DOCKER_ROOT:-/srv/docker}"
DEFAULT_NETWORK="bridge"
INTERACTIVE=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --interactive|-i)
            INTERACTIVE=true
            shift
            ;;
        --docker-root)
            DOCKER_ROOT="$2"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

# -----------------------------------------------------------------------------
# UTILITY FUNCTIONS
# -----------------------------------------------------------------------------

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

get_container_env() {
    local container="$1"
    local var="$2"
    docker inspect "$container" 2>/dev/null | \
        jq -r ".[0].Config.Env[] | select(startswith(\"$var=\")) | split(\"=\")[1]" 2>/dev/null || echo ""
}

add_entry() {
    local section="$1"
    local name="$2"
    shift 2
    
    # Check if entry exists
    local exists=$(yq e ".${section}[] | select(.name == \"$name\") | .name" "$CONFIG" 2>/dev/null || echo "")
    if [ -n "$exists" ]; then
        log "  Already in config: $name"
        return 0
    fi
    
    # Add entry
    yq eval ".${section} += [{\"name\": \"${name}\"}]" -i "$CONFIG"
    local idx=$(yq eval ".${section} | length - 1" "$CONFIG")
    
    # Add fields
    while [ $# -gt 0 ]; do
        local key="${1%%=*}"
        local value="${1#*=}"
        yq eval ".${section}[${idx}].${key} = \"${value}\"" -i "$CONFIG"
        shift
    done
    
    log "  Added to config: $name"
}

ask_confirm() {
    if [ "$INTERACTIVE" = false ]; then
        return 0
    fi
    
    local prompt="$1"
    read -p "$prompt [y/N] " -r response
    [[ "$response" =~ ^[yY]$ ]]
}

# -----------------------------------------------------------------------------
# INITIALIZATION
# -----------------------------------------------------------------------------

log "KDD - Database Discovery Starting"
log "Mode: $([ "$INTERACTIVE" = true ] && echo "Interactive (will ask for each DB)" || echo "Automatic (add all)")"
log "Docker root: $DOCKER_ROOT"

# Verify dependencies
if ! command_exists docker; then
    log "ERROR: docker not found! Mount socket: -v /var/run/docker.sock:/var/run/docker.sock"
    exit 1
fi

if ! command_exists yq || ! command_exists jq; then
    log "ERROR: yq or jq not found!"
    exit 1
fi

# Create base config
if [ ! -f "$CONFIG" ]; then
    cat <<EOF > "$CONFIG"
# Auto-generated by KDD setup.sh - $(date +'%Y-%m-%d %H:%M:%S')
mysql: []
postgres: []
mongo: []
EOF
    log "Created new config.yaml"
fi

# -----------------------------------------------------------------------------
# SCAN CONTAINERS
# -----------------------------------------------------------------------------

log "Scanning Docker containers..."
echo

containers=$(docker ps --format '{{.Names}}' 2>/dev/null || true)
if [ -z "$containers" ]; then
    log "No running containers found"
    exit 0
fi

while IFS= read -r container; do
    [ -z "$container" ] && continue
    
    image=$(docker inspect "$container" 2>/dev/null | jq -r '.[0].Config.Image' || echo "")
    [ -z "$image" ] && continue
    
    # Extract stack name (e.g., nextcloud_db_1 -> nextcloud)
    stackname=$(echo "$container" | sed 's/_[^_]*$//' | sed 's/_$//')
    
    # Get network
    network=$(docker inspect "$container" 2>/dev/null | \
        jq -r '.[0].NetworkSettings.Networks | keys[0]' || echo "$DEFAULT_NETWORK")
    
    # ---------------------------------------------------------------------
    # MYSQL / MARIADB
    # ---------------------------------------------------------------------
    if echo "$image" | grep -qiE 'mysql|mariadb'; then
        log "Found MySQL/MariaDB: $container ($image)"
        
        root_pass=$(get_container_env "$container" "MYSQL_ROOT_PASSWORD")
        db_name=$(get_container_env "$container" "MYSQL_DATABASE")
        db_user=$(get_container_env "$container" "MYSQL_USER")
        db_pass=$(get_container_env "$container" "MYSQL_PASSWORD")
        
        # MariaDB fallback
        [ -z "$root_pass" ] && root_pass=$(get_container_env "$container" "MARIADB_ROOT_PASSWORD")
        [ -z "$db_name" ] && db_name=$(get_container_env "$container" "MARIADB_DATABASE")
        [ -z "$db_user" ] && db_user=$(get_container_env "$container" "MARIADB_USER")
        [ -z "$db_pass" ] && db_pass=$(get_container_env "$container" "MARIADB_PASSWORD")
        
        # Determine credentials
        if [ -n "$root_pass" ]; then
            user="root"
            pass="$root_pass"
        elif [ -n "$db_user" ] && [ -n "$db_pass" ]; then
            user="$db_user"
            pass="$db_pass"
        else
            log "  No credentials found, skipping"
            echo
            continue
        fi
        
        db_name=${db_name:-$stackname}
        
        log "  Database: $db_name (user: $user)"
        
        if ask_confirm "  Add $container to backup config?"; then
            add_entry "mysql" "$stackname" \
                "host=$container" \
                "port=3306" \
                "dbname=$db_name" \
                "user=$user" \
                "password=$pass" \
                "network=$network"
        else
            log "  Skipped by user"
        fi
        echo
    fi
    
    # ---------------------------------------------------------------------
    # POSTGRESQL
    # ---------------------------------------------------------------------
    if echo "$image" | grep -qiE 'postgres'; then
        log "Found PostgreSQL: $container ($image)"
        
        db_name=$(get_container_env "$container" "POSTGRES_DB")
        db_user=$(get_container_env "$container" "POSTGRES_USER")
        db_pass=$(get_container_env "$container" "POSTGRES_PASSWORD")
        
        if [ -z "$db_user" ] || [ -z "$db_pass" ]; then
            log "  No credentials found, skipping"
            echo
            continue
        fi
        
        db_name=${db_name:-$stackname}
        
        log "  Database: $db_name (user: $db_user)"
        
        if ask_confirm "  Add $container to backup config?"; then
            add_entry "postgres" "$stackname" \
                "host=$container" \
                "port=5432" \
                "dbname=$db_name" \
                "user=$db_user" \
                "password=$db_pass" \
                "network=$network"
        else
            log "  Skipped by user"
        fi
        echo
    fi
    
    # ---------------------------------------------------------------------
    # MONGODB
    # ---------------------------------------------------------------------
    if echo "$image" | grep -qiE 'mongo'; then
        log "Found MongoDB: $container ($image)"
        
        db_user=$(get_container_env "$container" "MONGO_INITDB_ROOT_USERNAME")
        db_pass=$(get_container_env "$container" "MONGO_INITDB_ROOT_PASSWORD")
        db_name=$(get_container_env "$container" "MONGO_INITDB_DATABASE")
        
        if [ -z "$db_user" ] || [ -z "$db_pass" ]; then
            log "  No credentials found, skipping"
            echo
            continue
        fi
        
        db_name=${db_name:-$stackname}
        
        log "  Database: $db_name (user: $db_user)"
        
        if ask_confirm "  Add $container to backup config?"; then
            add_entry "mongo" "$stackname" \
                "host=$container" \
                "port=27017" \
                "dbname=$db_name" \
                "user=$db_user" \
                "password=$db_pass" \
                "authdb=admin" \
                "network=$network"
        else
            log "  Skipped by user"
        fi
        echo
    fi
    
done <<< "$containers"

# -----------------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------------

mysql_count=$(yq e '.mysql | length' "$CONFIG")
postgres_count=$(yq e '.postgres | length' "$CONFIG")
mongo_count=$(yq e '.mongo | length' "$CONFIG")
total=$((mysql_count + postgres_count + mongo_count))

log "=========================================="
log "Discovery completed"
log "=========================================="
log "Databases in config:"
log "  MySQL/MariaDB: $mysql_count"
log "  PostgreSQL: $postgres_count"
log "  MongoDB: $mongo_count"
log "  Total: $total"
log ""
log "Config saved to: $CONFIG"
log ""

if [ "$total" -eq 0 ]; then
    log "WARNING: No databases configured"
    log "Run with --interactive to select databases manually"
    exit 1
fi

log "Next steps:"
log "1. Review config: cat $CONFIG"
log "2. Test backup: /app/backup.sh"
log "3. Setup scheduled backups via Komodo Procedure"

exit 0